/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckAuthStatus500Response
 */
export interface CheckAuthStatus500Response {
    /**
     * Internal server error
     * @type {string}
     * @memberof CheckAuthStatus500Response
     */
    message: string;
}

/**
 * Check if a given object implements the CheckAuthStatus500Response interface.
 */
export function instanceOfCheckAuthStatus500Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CheckAuthStatus500ResponseFromJSON(json: any): CheckAuthStatus500Response {
    return CheckAuthStatus500ResponseFromJSONTyped(json, false);
}

export function CheckAuthStatus500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAuthStatus500Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function CheckAuthStatus500ResponseToJSON(value?: CheckAuthStatus500Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

