/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckAuthStatus200Response
 */
export interface CheckAuthStatus200Response {
    /**
     * Whether the user is authenticated.
     * @type {boolean}
     * @memberof CheckAuthStatus200Response
     */
    isAuthenticated: boolean;
    /**
     * Whether the user's email is verified.
     * @type {boolean}
     * @memberof CheckAuthStatus200Response
     */
    isEmailVerified: boolean;
}

/**
 * Check if a given object implements the CheckAuthStatus200Response interface.
 */
export function instanceOfCheckAuthStatus200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isAuthenticated" in value;
    isInstance = isInstance && "isEmailVerified" in value;

    return isInstance;
}

export function CheckAuthStatus200ResponseFromJSON(json: any): CheckAuthStatus200Response {
    return CheckAuthStatus200ResponseFromJSONTyped(json, false);
}

export function CheckAuthStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAuthStatus200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAuthenticated': json['isAuthenticated'],
        'isEmailVerified': json['isEmailVerified'],
    };
}

export function CheckAuthStatus200ResponseToJSON(value?: CheckAuthStatus200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAuthenticated': value.isAuthenticated,
        'isEmailVerified': value.isEmailVerified,
    };
}

