/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * APIs for user management and authentication. Double CSRF protection is used, therefore, the client must send the CSRF token in both the cookie and the request header for the non-GET requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface GetAllUsers200Response
 */
export interface GetAllUsers200Response {
    /**
     * 
     * @type {Array<UserProfile>}
     * @memberof GetAllUsers200Response
     */
    userProfileList: Array<UserProfile>;
}

/**
 * Check if a given object implements the GetAllUsers200Response interface.
 */
export function instanceOfGetAllUsers200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userProfileList" in value;

    return isInstance;
}

export function GetAllUsers200ResponseFromJSON(json: any): GetAllUsers200Response {
    return GetAllUsers200ResponseFromJSONTyped(json, false);
}

export function GetAllUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllUsers200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userProfileList': ((json['userProfileList'] as Array<any>).map(UserProfileFromJSON)),
    };
}

export function GetAllUsers200ResponseToJSON(value?: GetAllUsers200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userProfileList': ((value.userProfileList as Array<any>).map(UserProfileToJSON)),
    };
}

