/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatistics200Response
 */
export interface GetStatistics200Response {
    /**
     * The beginning of today in ISO 8601 format.
     * @type {string}
     * @memberof GetStatistics200Response
     */
    todayBeginDateTime: string;
    /**
     * The date and time 7 days ago in ISO 8601 format.
     * @type {string}
     * @memberof GetStatistics200Response
     */
    sevenDaysAgoDateTime: string;
    /**
     * The total number of users who have signed up.
     * @type {number}
     * @memberof GetStatistics200Response
     */
    totalUsers: number;
    /**
     * The total number of users with active sessions today.
     * @type {number}
     * @memberof GetStatistics200Response
     */
    activeUsersToday: number;
    /**
     * The average number of active session users in the last 7 days rolling.
     * @type {number}
     * @memberof GetStatistics200Response
     */
    averageActiveUsersLast7Days: number;
}

/**
 * Check if a given object implements the GetStatistics200Response interface.
 */
export function instanceOfGetStatistics200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "todayBeginDateTime" in value;
    isInstance = isInstance && "sevenDaysAgoDateTime" in value;
    isInstance = isInstance && "totalUsers" in value;
    isInstance = isInstance && "activeUsersToday" in value;
    isInstance = isInstance && "averageActiveUsersLast7Days" in value;

    return isInstance;
}

export function GetStatistics200ResponseFromJSON(json: any): GetStatistics200Response {
    return GetStatistics200ResponseFromJSONTyped(json, false);
}

export function GetStatistics200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatistics200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'todayBeginDateTime': json['todayBeginDateTime'],
        'sevenDaysAgoDateTime': json['sevenDaysAgoDateTime'],
        'totalUsers': json['totalUsers'],
        'activeUsersToday': json['activeUsersToday'],
        'averageActiveUsersLast7Days': json['averageActiveUsersLast7Days'],
    };
}

export function GetStatistics200ResponseToJSON(value?: GetStatistics200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'todayBeginDateTime': value.todayBeginDateTime,
        'sevenDaysAgoDateTime': value.sevenDaysAgoDateTime,
        'totalUsers': value.totalUsers,
        'activeUsersToday': value.activeUsersToday,
        'averageActiveUsersLast7Days': value.averageActiveUsersLast7Days,
    };
}

