/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface Login200Response
 */
export interface Login200Response {
    /**
     * Always true if the user is authenticated.
     * @type {boolean}
     * @memberof Login200Response
     */
    isAuthenticated: boolean;
    /**
     * Whether the user's email is verified.
     * @type {boolean}
     * @memberof Login200Response
     */
    isEmailVerified: boolean;
    /**
     * 
     * @type {UserProfile}
     * @memberof Login200Response
     */
    userProfile: UserProfile;
}

/**
 * Check if a given object implements the Login200Response interface.
 */
export function instanceOfLogin200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isAuthenticated" in value;
    isInstance = isInstance && "isEmailVerified" in value;
    isInstance = isInstance && "userProfile" in value;

    return isInstance;
}

export function Login200ResponseFromJSON(json: any): Login200Response {
    return Login200ResponseFromJSONTyped(json, false);
}

export function Login200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAuthenticated': json['isAuthenticated'],
        'isEmailVerified': json['isEmailVerified'],
        'userProfile': UserProfileFromJSON(json['userProfile']),
    };
}

export function Login200ResponseToJSON(value?: Login200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAuthenticated': value.isAuthenticated,
        'isEmailVerified': value.isEmailVerified,
        'userProfile': UserProfileToJSON(value.userProfile),
    };
}

