/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * APIs for user management and authentication. Double CSRF protection is used, therefore, the client must send the CSRF token in both the cookie and the request header for the non-GET requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout403Response
 */
export interface Logout403Response {
    /**
     * 
     * @type {string}
     * @memberof Logout403Response
     */
    message: string;
}

/**
 * Check if a given object implements the Logout403Response interface.
 */
export function instanceOfLogout403Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function Logout403ResponseFromJSON(json: any): Logout403Response {
    return Logout403ResponseFromJSONTyped(json, false);
}

export function Logout403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout403Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Logout403ResponseToJSON(value?: Logout403Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

