/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout200Response
 */
export interface Logout200Response {
    /**
     * Logout successful
     * @type {string}
     * @memberof Logout200Response
     */
    message: string;
}

/**
 * Check if a given object implements the Logout200Response interface.
 */
export function instanceOfLogout200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function Logout200ResponseFromJSON(json: any): Logout200Response {
    return Logout200ResponseFromJSONTyped(json, false);
}

export function Logout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function Logout200ResponseToJSON(value?: Logout200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

