/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * This is a User Management & Authentication API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendVerificationEmail200Response
 */
export interface SendVerificationEmail200Response {
    /**
     * The token expiration time in ISO 8601 format.
     * @type {string}
     * @memberof SendVerificationEmail200Response
     */
    tokenExpireDateTime: string;
}

/**
 * Check if a given object implements the SendVerificationEmail200Response interface.
 */
export function instanceOfSendVerificationEmail200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenExpireDateTime" in value;

    return isInstance;
}

export function SendVerificationEmail200ResponseFromJSON(json: any): SendVerificationEmail200Response {
    return SendVerificationEmail200ResponseFromJSONTyped(json, false);
}

export function SendVerificationEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendVerificationEmail200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenExpireDateTime': json['tokenExpireDateTime'],
    };
}

export function SendVerificationEmail200ResponseToJSON(value?: SendVerificationEmail200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenExpireDateTime': value.tokenExpireDateTime,
    };
}

