/* tslint:disable */
/* eslint-disable */
/**
 * User Management System - API
 * APIs for user management and authentication. Double CSRF protection is used, therefore, the client must send the CSRF token in both the cookie and the request header for the non-GET requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cocoychris@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyProfileRequest
 */
export interface UpdateMyProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyProfileRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateMyProfileRequest interface.
 */
export function instanceOfUpdateMyProfileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function UpdateMyProfileRequestFromJSON(json: any): UpdateMyProfileRequest {
    return UpdateMyProfileRequestFromJSONTyped(json, false);
}

export function UpdateMyProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateMyProfileRequestToJSON(value?: UpdateMyProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

